### ISSUE TITLE
حذف فونت رویا 

### ISSUE THREAD

**Issue by MJafarMashhadi** [SutCEGoS/website#6]
چون از این فونت در سایت استفاده نمی‌شود دانلود آن در css ها بی مورد است

**Comment by Khedesh** [comment]
یعنی royafont.css  رو پاک کنم؟

**Comment by MJafarMashhadi** [comment]
بله، به علاوه اینکه چک شه توی CSS های سایت که جایی استفاده نشده باشه. اگر شده بود با فونت Iran sans جایگزین شه

**Comment by Khedesh** [comment]
این کار هم انجام شد.

**Comment by MJafarMashhadi** [comment]
بهتره که در 
commit message
شمارهٔ این 
issue
ذکر بشه :)
